### ISSUE TITLE
Cannot request reviewers

### ISSUE THREAD

**Issue by mattcalder-meta** [prestodb/rfcs#19]
Created a pull request https://github.com/prestodb/rfcs/pull/16 but cannot request reviewers. Seems like a permissions issue but not sure what to do. 
<img width="273" alt="requestreviewers" src="https://github.com/user-attachments/assets/5d29412d-8477-4e42-b756-fd7b8558f8d1">

**Comment by tdcmeehan** [comment]
I'll add you as a contributor to Presto, which will give you these permissions.
